name: amura
favicon: null
layout_spectrum: 0.5106865121051669
typography_spectrum: 0.759226095629856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c1dd02'
    - '#ffffff'
    - '#2a2522'
    - '#6b6967'
    - '#b4b3b2'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
